"use strict";
const START=480,END=1320,MAX_FRIENDSHIP=60,TIME_SCALE=2;
const blankInventory=()=>Object.fromEntries(Object.keys(ITEM_DATA).map(id=>[id,0]));
const blankDailyItems=()=>Object.fromEntries(Object.keys(LOCATION_DATA).map(id=>[id,false]));
const gameState={day:1,minutes:START,currentLocation:"cafe",inventory:blankInventory(),dailyItems:blankDailyItems(),discoveredItems:[],itemGuideSeen:false,ended:false};
const viewState={screen:"map",activeNpcId:null,eventStep:0};
const $=s=>document.querySelector(s);
const EVENT_DATA=RELATION_EVENT_DATA;
const el={day:$("#day-display"),time:$("#time-display"),location:$("#location-display"),hint:$("#status-hint"),dailyHint:$("#daily-hint"),period:$("#period-badge"),locationList:$("#location-list"),mapView:$("#map-view"),sceneView:$("#scene-view"),sceneTitle:$("#scene-title"),sceneDescription:$("#scene-description"),npcFigures:$("#npc-figures"),npcStatus:$("#npc-status"),relationList:$("#relation-list"),timeMessage:$("#time-message"),back:$("#back-to-map"),sceneActions:$("#scene-actions"),talk:$("#talk-button"),gift:$("#gift-button"),target:$("#interaction-target"),eventEntry:$("#event-entry"),endDay:$("#end-day-button"),dialogueModal:$("#dialogue-modal"),dialogueAvatar:$("#dialogue-avatar"),dialogueName:$("#dialogue-name"),dialogueLine:$("#dialogue-line"),dialogueFeedback:$("#dialogue-feedback"),dialogueChoices:$("#dialogue-choices"),dialogueContinue:$("#dialogue-continue"),giftModal:$("#gift-modal"),giftRecipient:$("#gift-recipient"),giftMessage:$("#gift-message"),giftOptions:$("#gift-options"),relationshipModal:$("#relationship-modal"),upgradeAvatar:$("#upgrade-avatar"),relationshipMessage:$("#relationship-message"),clueModal:$("#clue-modal"),clueTitle:$("#clue-title"),clueContent:$("#clue-content"),villagerModal:$("#villager-modal"),detailAvatar:$("#villager-detail-avatar"),detailName:$("#villager-detail-name"),detailStats:$("#villager-detail-stats"),detailClue:$("#villager-detail-clue"),eventModal:$("#event-modal"),eventLine:$("#event-line"),eventChoices:$("#event-choices"),eventContinue:$("#event-continue"),transition:$("#day-transition"),transitionDay:$("#transition-day"),heart:$("#floating-heart"),itemActions:$("#item-actions"),inventoryButton:$("#inventory-button"),inventoryCount:$("#inventory-count"),inventoryModal:$("#inventory-modal"),inventoryList:$("#inventory-list"),waitButton:$("#wait-button"),waitModal:$("#wait-modal"),itemModal:$("#item-modal"),itemIcon:$("#item-icon"),itemMessage:$("#item-message"),itemChoice:$("#item-choice"),itemConfirm:$("#item-confirm"),ending:$("#ending-screen"),endingResults:$("#ending-results"),restart:$("#restart-button")};
el.eventAvatar=$("#event-avatar");el.eventLabel=$("#event-label");el.eventSpeaker=$("#event-speaker");
const periodNames={morning:"上午",afternoon:"下午",dusk:"傍晚",night:"夜晚"};
function getTimePeriod(m=gameState.minutes){if(m<720)return"morning";if(m<1080)return"afternoon";if(m<1200)return"dusk";return"night"}
function formatTime(m){return`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}
function getNpc(id){return NPC_DATA.find(n=>n.id===id)}
function relationship(n){return GameRules.getRelationship(n.friendship)}
function scheduleFor(id){return SCHEDULE_DATA[gameState.day][id]}
function npcsAt(location){const p=getTimePeriod();return NPC_DATA.filter(n=>scheduleFor(n.id)[p]===location)}
function activeNpc(){return getNpc(viewState.activeNpcId)}
function statusFor(n){const p=getTimePeriod(),where=LOCATION_DATA[gameState.currentLocation].name;if(p==="night")return NIGHT_DIALOGUE[n.id][relationship(n)];return n.id==="emma"?`Emma 正在${where}安静地度过${periodNames[p]}。`:`Leo 正在${where}四处看看。`}
function renderLocations(){el.locationList.innerHTML=Object.entries(LOCATION_DATA).map(([id,l])=>`<button class="location-node ${id}" data-location="${id}" aria-label="前往${l.name}"><span class="building"></span><span class="node-label">${l.name}</span></button>`).join("")}
function renderRelations(){el.relationList.innerHTML=NPC_DATA.map(n=>`<button class="relation-row ${n.id}" data-villager="${n.id}" aria-label="查看 ${n.name} 详情"><span class="portrait">${n.avatar}</span><span class="relation-name">${n.name}<small>关系：${relationship(n)}</small></span><strong class="hearts">♥ ${n.friendship} / 60</strong></button>`).join("")}
function renderFigures(list){el.npcFigures.innerHTML=list.map(n=>`<button class="npc-figure ${n.id}${n.id===viewState.activeNpcId?" active":""}" data-npc="${n.id}" aria-label="选择 ${n.name}"><span class="npc-name">${n.name}</span><span class="npc-head">${n.avatar}</span><span class="npc-body"></span></button>`).join("")}
function availableEvent(){return Object.entries(EVENT_DATA).find(([id,e])=>{const n=getNpc(id);return GameRules.canTriggerRelationEvent({friendship:n.friendship,day:gameState.day,period:getTimePeriod(),location:gameState.currentLocation,triggered:n.specialEventTriggered},e)&&npcsAt(e.location).some(x=>x.id===id)})||null}
function render(){const loc=LOCATION_DATA[gameState.currentLocation],p=getTimePeriod(),present=npcsAt(gameState.currentLocation);if(present.length===1)viewState.activeNpcId=present[0].id;else if(!present.some(n=>n.id===viewState.activeNpcId))viewState.activeNpcId=null;const selected=activeNpc(),event=availableEvent();el.day.textContent=`Day ${gameState.day}`;el.time.textContent=formatTime(gameState.minutes);el.period.textContent=periodNames[p];el.dailyHint.textContent=`当前：${periodNames[p]} · ${p==="night"?"适合拜访熟悉的镇民":"下一阶段镇民可能改变行程"}`;el.location.textContent=viewState.screen==="map"?"小镇地图":loc.name;el.sceneTitle.textContent=loc.name;el.sceneDescription.textContent=loc.description;el.sceneView.className=`scene-view scene-${gameState.currentLocation}`;el.mapView.hidden=viewState.screen!=="map";el.sceneView.hidden=viewState.screen!=="scene";el.sceneActions.hidden=!selected;el.npcStatus.textContent=selected?statusFor(selected):present.length>1?DUO_LINE:"这里现在没有人。";el.target.textContent=selected?`当前互动：${selected.name}`:present.length>1?"点击人物选择互动对象":"";el.eventEntry.hidden=!(viewState.screen==="scene"&&event);if(event)el.eventEntry.textContent=`✦ ${getNpc(event[0]).name} 好像有话想和你说`;el.hint.textContent=event?`${getNpc(event[0]).name} 好像有话想和你说。`:gameState.day===2&&p==="dusk"&&gameState.currentLocation==="square"?DUO_LINE:viewState.screen==="map"?"三天里，每个地点都会出现不同的小发现。":selected?`你在${loc.name}遇见了 ${selected.name}。`:`${loc.name}里暂时很安静。`;renderFigures(present);renderRelations();renderItemActions();const ended=gameState.minutes>=END;el.timeMessage.textContent=ended?(gameState.day===3?"三日体验已结束":"今天已经结束了"):"时间流逝";el.endDay.hidden=!ended;el.endDay.textContent=gameState.day===3?"结束三日体验":"结束今天"}
function showHeart(v){el.heart.textContent=`♥ ${v>0?"+":""}${v}`;el.heart.classList.remove("show");void el.heart.offsetWidth;el.heart.classList.add("show")}
function applyFriendship(n,amount){const before=n.friendship;n.friendship=Math.min(MAX_FRIENDSHIP,Math.max(0,n.friendship+amount));const actual=n.friendship-before,upgrade=GameRules.getRelationshipUpgrade(before,n.friendship,n.name);n.unlockedScheduleLevel=GameRules.getClueLevel(n.friendship);renderRelations();showHeart(actual);return{upgrade,actual}}
function clueHtml(n){const level=n.unlockedScheduleLevel,s=scheduleFor(n.id);if(level==="unknown")return"<p>还不了解这位镇民的生活习惯。</p>";if(level==="habit")return n.id==="emma"?"<p>她经常在上午去咖啡店，也珍惜安静时间。</p>":"<p>他很喜欢在下午进行户外活动。</p>";let html=`<p><strong>${n.name} · Day ${gameState.day}</strong></p>${Object.entries(s).map(([p,l])=>`<p>${periodNames[p]}：${LOCATION_DATA[l].name}</p>`).join("")}`;if(level==="current")html+=`<p class="current-clue">${n.name} 现在可能在${LOCATION_DATA[s[getTimePeriod()]].name}。</p>`;return html}
function openUpgrade(n,u){el.upgradeAvatar.textContent=n.avatar;el.relationshipMessage.textContent=u.message;el.relationshipModal.dataset.clueNpc=n.id;el.relationshipModal.hidden=false}
function openClue(n){el.clueTitle.textContent=n.unlockedScheduleLevel==="habit"?"生活习惯已解锁":n.unlockedScheduleLevel==="plan"?"今日计划已解锁":"当前位置线索已解锁";el.clueContent.innerHTML=clueHtml(n);el.clueModal.hidden=false}
function nightAccess(n){return relationship(n)!=="陌生"||(n.giftedToday&&n.completedConversations.filter(k=>k.startsWith(`${gameState.day}:`)).length>=3)}
function mainConversation(){const n=activeNpc(),p=getTimePeriod();if(!n||(p==="night"&&!nightAccess(n)))return null;return Object.entries(DIALOGUE_DATA_V2[n.id][gameState.day]).find(([,d])=>d.period===p&&d.location===gameState.currentLocation)||null}
function talk(){const n=activeNpc();if(!n)return;el.dialogueAvatar.textContent=n.avatar;el.dialogueName.textContent=n.name;el.dialogueFeedback.textContent="";el.dialogueModal.dataset.upgrade="";const found=mainConversation();if(!found){el.dialogueLine.textContent=NIGHT_DIALOGUE[n.id][relationship(n)];el.dialogueChoices.innerHTML="";el.dialogueContinue.hidden=false;el.dialogueFeedback.textContent=getTimePeriod()==="night"&&relationship(n)==="陌生"?"关系还不够熟悉 · ♥ +0":"夜间闲聊 · ♥ +0"}else{const[id,d]=found,key=`${gameState.day}:${id}`;if(n.completedConversations.includes(key)){el.dialogueLine.textContent=REPEAT_DIALOGUE[n.id];el.dialogueChoices.innerHTML="";el.dialogueContinue.hidden=false;el.dialogueFeedback.textContent="这段主要对话已经完成 · ♥ +0"}else{el.dialogueLine.textContent=d.opening[relationship(n)];el.dialogueChoices.innerHTML=d.choices.map((c,i)=>`<button data-dialogue-choice="${i}">${c.text}</button>`).join("");el.dialogueContinue.hidden=true;el.dialogueModal.dataset.npcId=n.id;el.dialogueModal.dataset.conversationId=id}}el.dialogueModal.hidden=false}
function chooseDialogue(i){const n=getNpc(el.dialogueModal.dataset.npcId),id=el.dialogueModal.dataset.conversationId,key=`${gameState.day}:${id}`;if(!n||n.completedConversations.includes(key))return;const d=DIALOGUE_DATA_V2[n.id][gameState.day][id],c=d.choices[i];n.completedConversations.push(key);const result=applyFriendship(n,c.value);el.dialogueLine.textContent=c.response;el.dialogueChoices.innerHTML="";el.dialogueContinue.hidden=false;el.dialogueFeedback.textContent=n.friendship===60&&result.actual===0&&c.value>0?"关系已经非常亲近。":`♥ ${result.actual>0?"+":""}${result.actual}`;el.dialogueModal.dataset.upgrade=result.upgrade?JSON.stringify({id:n.id,u:result.upgrade}):""}
function giftCooling(n,id){return n.giftHistory[id]&&gameState.day-n.giftHistory[id]<2}
function openGift(){const n=activeNpc();if(!n)return;el.giftModal.dataset.npcId=n.id;el.giftModal.dataset.upgrade="";el.giftRecipient.textContent=`送给 ${n.name}`;el.giftMessage.textContent=n.giftedToday?`今天已经给 ${n.name} 送过礼物了。`:"选择一份持有的礼物表达心意。";el.giftOptions.innerHTML=Object.entries(ITEM_DATA).map(([id,it])=>`<button data-gift="${id}" ${n.giftedToday||gameState.inventory[id]===0?"disabled":""}><span>${it.icon}</span><strong>${it.name}</strong><small>×${gameState.inventory[id]}${giftCooling(n,id)?" · 冷却中":""}</small></button>`).join("");el.giftModal.hidden=false}
function giveGift(id){const n=getNpc(el.giftModal.dataset.npcId);if(!n||n.giftedToday||!gameState.inventory[id])return;if(giftCooling(n,id)){el.giftMessage.textContent=`${n.name}：前两天你才送过我这个呢，还是留着吧。`;return}const gift=GIFT_DATA[n.id][id];gameState.inventory[id]--;n.giftedToday=true;n.giftHistory[id]=gameState.day;const result=applyFriendship(n,gift.value);el.giftMessage.innerHTML=`<strong>${n.name}：</strong>${gift.reply}<span>${n.friendship===60&&result.actual===0&&gift.value>0?"关系已经非常亲近。":`♥ ${result.actual>0?"+":""}${result.actual}`}</span>`;el.giftOptions.querySelectorAll("button").forEach(b=>b.disabled=true);updateInventory();if(result.upgrade)el.giftModal.dataset.upgrade=JSON.stringify({id:n.id,u:result.upgrade})}
function canCollectHome(id){const owner=id==="emmaHome"?getNpc("emma"):getNpc("leo");return owner.friendship>=20&&npcsAt(id).some(n=>n.id===owner.id)}
function renderItemActions(){if(viewState.screen!=="scene"){el.itemActions.innerHTML="";return}const loc=gameState.currentLocation,id=DAILY_ITEMS[gameState.day][loc],done=gameState.dailyItems[loc],home=loc.endsWith("Home"),locked=home&&!canCollectHome(loc);el.itemActions.innerHTML=`<button data-collect="${id}" ${done||locked?"disabled":""}>${ITEM_DATA[id].icon} ${done?"今天已获得":locked?"关系熟悉后可获得":`获得${ITEM_DATA[id].name}`}</button>`}
function collectItem(){const loc=gameState.currentLocation,id=DAILY_ITEMS[gameState.day][loc];if(gameState.dailyItems[loc]||(loc.endsWith("Home")&&!canCollectHome(loc)))return;gameState.dailyItems[loc]=true;gameState.inventory[id]++;if(!gameState.discoveredItems.includes(id))gameState.discoveredItems.push(id);updateInventory();renderItemActions();showItem(id,ITEM_MESSAGES[id])}
function showItem(id,msg){el.itemIcon.textContent=ITEM_DATA[id].icon;el.itemMessage.textContent=(gameState.itemGuideSeen?"":"有些地点每天都会出现不同的小东西。 ")+msg;gameState.itemGuideSeen=true;el.itemChoice.innerHTML="";el.itemConfirm.hidden=false;el.itemModal.hidden=false}
function updateInventory(){el.inventoryCount.textContent=Object.values(gameState.inventory).reduce((a,b)=>a+b,0);el.inventoryList.innerHTML=Object.entries(ITEM_DATA).map(([id,it])=>`<div><span>${it.icon}</span><strong>${it.name}</strong><small>×${gameState.inventory[id]}</small></div>`).join("")}
function openVillager(id){const n=getNpc(id),pending=n.friendship>=40&&!n.specialEventTriggered?`<p class="current-clue">好像还有一些事情可以和 ${n.name} 一起经历。</p>`:"";el.detailAvatar.textContent=n.avatar;el.detailName.textContent=n.name;el.detailStats.textContent=`关系：${relationship(n)}　♥ ${n.friendship} / 60`;el.detailClue.innerHTML=clueHtml(n)+pending;el.villagerModal.hidden=false}
function closeModal(id){const m=$(`#${id}`);m.hidden=true;if(m.dataset.upgrade){const p=JSON.parse(m.dataset.upgrade);m.dataset.upgrade="";openUpgrade(getNpc(p.id),p.u)}else if(id==="relationship-modal"&&m.dataset.clueNpc){const n=getNpc(m.dataset.clueNpc);m.dataset.clueNpc="";openClue(n)}}
function waitTo(v){const target=v===60?Math.min(gameState.minutes+60,END):v;if(target>gameState.minutes)gameState.minutes=Math.min(target,END);el.waitModal.hidden=true;render()}
function openWait(){el.waitModal.querySelectorAll("[data-wait]").forEach(b=>{const v=Number(b.dataset.wait);b.disabled=gameState.minutes>=END||(v!==60&&gameState.minutes>=v)});el.waitModal.hidden=false}
function endDay(){if(gameState.minutes<END)return;if(gameState.day===3){showEnding();return}gameState.day++;gameState.minutes=START;gameState.currentLocation="cafe";gameState.dailyItems=blankDailyItems();viewState.screen="map";viewState.activeNpcId=null;NPC_DATA.forEach(n=>n.giftedToday=false);el.transitionDay.textContent=`Day ${gameState.day}`;el.transition.hidden=false;render();setTimeout(()=>el.transition.hidden=true,1050)}
function showEnding(){gameState.ended=true;const habits=n=>n.unlockedScheduleLevel==="unknown"?0:n.unlockedScheduleLevel==="habit"?1:4;el.endingResults.innerHTML=NPC_DATA.map(n=>`<article><h2>${n.name}</h2><p>关系：${relationship(n)}</p><strong>♥ ${n.friendship} / 60</strong><p>了解的生活习惯：${habits(n)}</p><p>完成关系事件：${n.specialEventTriggered?1:0}</p></article>`).join("")+`<article><h2>小镇探索</h2><strong>发现物品：${gameState.discoveredItems.length} / 15</strong></article>`;el.ending.hidden=false}
function startEvent(){const found=availableEvent();if(!found)return;const[id,e]=found;viewState.eventStep=0;viewState.eventNpcId=id;el.eventAvatar.textContent=getNpc(id).avatar;el.eventAvatar.className=`modal-portrait ${id}`;el.eventSpeaker.textContent=getNpc(id).name;el.eventLabel.textContent=`关系事件 · ${e.title}`;el.eventLine.textContent=e.lines[0];el.eventChoices.innerHTML="";el.eventContinue.hidden=false;el.eventModal.hidden=false}
function continueEvent(){const e=EVENT_DATA[viewState.eventNpcId];viewState.eventStep++;if(viewState.eventStep<e.lines.length){el.eventLine.textContent=e.lines[viewState.eventStep];if(viewState.eventStep===2){el.eventContinue.hidden=true;el.eventChoices.innerHTML='<button data-event-choice="yes">一起去吧</button><button data-event-choice="no">今天先不了</button>'}}else{el.eventModal.hidden=true;render()}}
function chooseEvent(c){const id=viewState.eventNpcId,n=getNpc(id),e=EVENT_DATA[id];n.specialEventTriggered=true;el.eventChoices.innerHTML="";el.eventContinue.hidden=false;el.eventLine.textContent=c==="yes"?`${e.yes} 已完成关系事件：${e.title}`:e.no}
function isPaused(){return gameState.ended||document.hidden||Boolean(document.querySelector('.modal-layer:not([hidden]),.day-transition:not([hidden]),.ending-layer:not([hidden])'))}
function setFriendship(id,v){const n=getNpc(id);n.friendship=Math.min(60,Math.max(0,Number(v)||0));n.unlockedScheduleLevel=GameRules.getClueLevel(n.friendship);render();return`${n.name}: ${n.friendship} (${relationship(n)})`}
function calculateMaxFriendshipByDay(id){const days=[1,2,3].map(day=>{const dialogueMax=Object.values(DIALOGUE_DATA_V2[id][day]).reduce((sum,c)=>sum+Math.max(...c.choices.map(o=>o.value)),0),giftId=BEST_GIFTS[id][day],giftMax=GIFT_DATA[id][giftId].value;return{day,dialogueMax,giftId,giftMax,total:dialogueMax+giftMax}});return{id,days,threeDayTotal:days.reduce((sum,d)=>sum+d.total,0)}}
el.locationList.addEventListener("click",e=>{const b=e.target.closest("[data-location]");if(!b)return;gameState.currentLocation=b.dataset.location;viewState.screen="scene";viewState.activeNpcId=null;render();if(!gameState.itemGuideSeen){gameState.itemGuideSeen=true;el.itemIcon.textContent="🎁";el.itemMessage.textContent="有些地点每天都会出现不同的小东西，试试场景中的物品按钮吧。";el.itemModal.hidden=false}});
el.npcFigures.addEventListener("click",e=>{const b=e.target.closest("[data-npc]");if(b){viewState.activeNpcId=b.dataset.npc;render()}});el.relationList.addEventListener("click",e=>{const b=e.target.closest("[data-villager]");if(b)openVillager(b.dataset.villager)});el.back.addEventListener("click",()=>{viewState.screen="map";viewState.activeNpcId=null;render()});el.talk.addEventListener("click",talk);el.gift.addEventListener("click",openGift);el.dialogueChoices.addEventListener("click",e=>{const b=e.target.closest("[data-dialogue-choice]");if(b)chooseDialogue(Number(b.dataset.dialogueChoice))});el.giftOptions.addEventListener("click",e=>{const b=e.target.closest("[data-gift]");if(b&&!b.disabled)giveGift(b.dataset.gift)});el.itemActions.addEventListener("click",e=>{if(e.target.closest("[data-collect]"))collectItem()});el.inventoryButton.addEventListener("click",()=>{updateInventory();el.inventoryModal.hidden=false});el.waitButton.addEventListener("click",openWait);el.waitModal.addEventListener("click",e=>{const b=e.target.closest("[data-wait]");if(b&&!b.disabled)waitTo(Number(b.dataset.wait))});el.endDay.addEventListener("click",endDay);el.restart.addEventListener("click",()=>location.reload());el.eventEntry.addEventListener("click",startEvent);el.eventContinue.addEventListener("click",continueEvent);el.eventChoices.addEventListener("click",e=>{const b=e.target.closest("[data-event-choice]");if(b)chooseEvent(b.dataset.eventChoice)});document.querySelectorAll("[data-close-modal]").forEach(b=>b.addEventListener("click",()=>closeModal(b.dataset.closeModal)));
setInterval(()=>{if(isPaused()||gameState.minutes>=END)return;const before=getTimePeriod();gameState.minutes=Math.min(END,gameState.minutes+TIME_SCALE);const after=getTimePeriod();el.time.textContent=formatTime(gameState.minutes);if(before!==after||gameState.minutes>=END)render()},1000);
renderLocations();render();updateInventory();window.setFriendship=setFriendship;window.calculateMaxFriendshipByDay=calculateMaxFriendshipByDay;window.DayGame={gameState,getTimePeriod,npcsAt,waitTo,endDay,render,setFriendship,calculateMaxFriendshipByDay,TIME_SCALE};

